compiler:
- g++
os:
- linux
addons:
  apt:
    packages:
    - g++-4.9
env:
  global:
    - secure: "c9CezEJjUr+dCgL5dfGurLDzqB5WarCx5aK1MTPM5jjGRIr3BlyEAWsADPf3yRwfVf4zDTBgHTxt+MmyYyftN3OQvXXI247TFGJuHqq5DRaHJEb7/o/ePcjGHdc8jTA74SMiy40+FCRmLOWRnKk8WHl2rSBnCHx91t0s0PTS+tsQc8lIz0a5VufTQb2WnHo3uTIn/tvzPM+V5rxgRuueDe42nksq/pAYHjhwr9sENTbtOTu5bL+T5ATeSi7jMcGPt9ou2GtUZhSzUSttn3pto1t55HhsXIdwZ/vOQpTsxu3oozNDB3Phzd+YZDNc81Rl17J23cWDpMWaAAn/DvSZ3pk231NpXCFrJwSFugd067xWMItLENdDEnjC0oXlHom7lPC1Wo6II0b+IhSl7QmRczheNP2Xf/YtHmAFwf9vlsPCQebkaLrq9qqRq2z275QNS+i/aH1LOAWsP/4oQB9NyW4JSUCxyliCpBk4LCVDKc1dNj3Cep3/+pwvbXz+HSiD4qsWOMLekugz3BtNCbVPBrQ2XhOrZm2ZwKkXRP1IQQE+Bhmv6OWfmNg66iKn59poF0r/RtUoHf8qzdRlVYRrUc1/EUtR52PJz2kkR1YoIMYezW+8dmrpZRw/lm0qMPwZnv2KuaeCgIU4jvcd7tg6qLcUoqL3xKB5TeSFuaSMo+M="
    - secure: "Tv6d8MSq11A8PFdJrxOKJrsMxsQO2OTip03p+NUdokj44cIxpjKwpujaod0ap/VgHRslKkGTV1dKpcnHPL/LwEQmsmreNWThb0dSSHAFrCoMhTTU4W6CAko46NjsYzHkZvvSZcXTCoBpwpG8/nLCUVUqzDDa6Z2EAcB8UEy6bwgbT4TW9SEhnuYp1y0dcZ90Zfgl2uQ4ZHyiLY0ZlxTWpKYHy8OmPuIDEQ6eBIkxjSDgU/shtoUtt0vkVuZFFVxrDTlKk2H5btv6vqa75iMDZpDDwW8we1I54Jmgcb6qNETW/XRI2QZ4H0C+41nhGXBLOlSoX1p4XTXFFsoqUdFuUm0RFC6jJlqnGwG1S3pLQY+fZiCKDaU5526cFpANAoYYGhm/Pn2e9IxpKgFP8I5sRFYEb6IvBgtoi7V48cPCqsrVFzTgNwWHB5+hOPtqURsInYgHallAO6VvixFMRWnSI+ItiUtBjOiAxD1zF+1xWQ84nZxRTnNJZhCipPDd0z0AoFS+HQFQuHX7VJdlTYv/PJLXwOv6jlxf1MQDfhbxT+5cV0oMPDc8aEIvokt617U7Unvow6xJFhqDCev8nTnKjZo73n3kEJUdFKans9gg7Kb4n2rtzTJa7sBaMLgUyULAuEFryUvqZ/OsxFJHhytC7aKUcf/tD6qh0MwnHEwi66U="
    - ISEARCH_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

before_install:
- eval "${ISEARCH_EVAL}"

install:
- sudo apt-get install snappy libsnappy-dev zlib1g zlib1g-dev bzip2 liblz4-dev libasan0 openssl libmxml-dev jq
- sudo apt update
- sudo apt install gcc-4.8
- sudo apt install g++-4.8
- sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 20
- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 20

script:
- cd ../
- mkdir rocksdb
- cd rocksdb
- wget http://storage.jd.com/lbs-search-acc/librocksdb.so.6.6.0
- cd ../
- git clone https://github.com/gflags/gflags.git
- cd gflags
- git checkout -b 2.2 v2.2.2
- cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DBUILD_SHARED_LIBS=ON -DGFLAGS_NAMESPACE=google -G "Unix Makefiles" .
- make
- cd ../isearch
- sh build.sh

after_success:
- cp src/search_agent/bin/search_agent dockerfiles/agent/
- cp resource/search_agent/conf/sa.conf dockerfiles/agent/
- cp src/search_agent/bin/search_agent dockerfiles/search_local
- cp -r resource dockerfiles/search_local
- cp ../rocksdb/librocksdb.so.6.6.0 dockerfiles/search_local
- cp /home/travis/build/jdisearch/gflags/lib/libgflags.so.2.2.2 dockerfiles/search_local
- cp src/search_local/index_storage/cache/dtcd dockerfiles/search_local
- cp src/search_local/index_storage/rocksdb_helper/rocksdb_helper dockerfiles/search_local
- cp src/search_local/index_storage/api/c_api_cc/libdtc-gcc-4.8-r4646582.so dockerfiles/search_local
- cp src/search_local/index_write/bin/index_write dockerfiles/search_local
- cp src/search_local/index_read/bin/index_read dockerfiles/search_local

- cd dockerfiles/agent
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker build -t $DOCKER_USERNAME/search_agent:latest .
- docker push $DOCKER_USERNAME/search_agent:latest

- cd ../cache
- docker build -t $DOCKER_USERNAME/search_local:latest .
- docker push $DOCKER_USERNAME/search_local:latest